version: '2'
services:
  xdq-redis:
    restart: always
    image: redis:6.2.1-alpine
    ports:
      - '6379:6379'
  xdq-mongo:
    restart: always
    image: mongo:xenial
    command: mongod --dbpath /data/db --replSet myset
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - '27017:27017'